name: "Publish"
on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Npm and Node Setup
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Edit
        if: github.event_name != 'release'
        shell: node {0}
        run: |
          const fs = require('fs');
          const Package_JSon = JSON.parse(fs.readFileSync(process.cwd()+'/package.json', 'utf8'));
          const run_ID = "${{ github.run_id }}";
          Package_JSon.version = `${run_ID.slice(0, 2)}.${run_ID.slice(3, 6)}.${run_ID.slice(7, 11)}`;
          fs.writeFileSync(process.cwd()+'/package.json', JSON.stringify(Package_JSon, null, 2));
          console.log(Package_JSon.version);

      - name: Install Dependencies
        run: npm install -d

      - name: Release Publish
        if: github.event_name == 'release'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}

      - name: Release Publish Next
        if: github.event_name != 'release'
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}
